-- MySQL Script generated by MySQL Workbench
-- Tue Jan 28 11:32:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hospital` DEFAULT CHARACTER SET utf8 ;
USE `Hospital` ;

-- -----------------------------------------------------
-- Table `Hospital`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Departments` (
  `department_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Doctors` (
  `doctors_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `specialization` VARCHAR(45) NOT NULL,
  `department_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`doctors_id`),
  INDEX `department_id_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `department_id`
    FOREIGN KEY (`department_id`)
    REFERENCES `Hospital`.`Departments` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Nurses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Nurses` (
  `nurses_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `assigned_id_department` BIGINT(20) NOT NULL,
  PRIMARY KEY (`nurses_id`),
  INDEX `assigned_id_department_idx` (`assigned_id_department` ASC) VISIBLE,
  CONSTRAINT `assigned_id_department`
    FOREIGN KEY (`assigned_id_department`)
    REFERENCES `Hospital`.`Departments` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Patients` (
  `patients_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `contact_number` INT NOT NULL,
  PRIMARY KEY (`patients_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Appointments` (
  `appointments_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `patient_id_appointments` BIGINT(20) NOT NULL,
  `doctor_id_appointments` BIGINT(20) NOT NULL,
  `appointment_date` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`appointments_id`),
  INDEX `patient_id_appointments_idx` (`patient_id_appointments` ASC) VISIBLE,
  INDEX `doctor_id_appointments_idx` (`doctor_id_appointments` ASC) VISIBLE,
  CONSTRAINT `patient_id_appointments`
    FOREIGN KEY (`patient_id_appointments`)
    REFERENCES `Hospital`.`Patients` (`patients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `doctor_id_appointments`
    FOREIGN KEY (`doctor_id_appointments`)
    REFERENCES `Hospital`.`Doctors` (`doctors_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`LabTest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`LabTest` (
  `labTest_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`labTest_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`TestResults`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`TestResults` (
  `test_results_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `patient_id_test_result` BIGINT(20) NOT NULL,
  `lab_test_id_test_result` BIGINT(20) NOT NULL,
  `test_date` DATE NOT NULL,
  `doctor_id_test_result` BIGINT(20) NOT NULL,
  `result` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`test_results_id`),
  INDEX `patient_id_test_result_idx` (`patient_id_test_result` ASC) VISIBLE,
  INDEX `lab_test_id_test_result_idx` (`lab_test_id_test_result` ASC) VISIBLE,
  INDEX `doctor_id_test_result_idx` (`doctor_id_test_result` ASC) VISIBLE,
  CONSTRAINT `patient_id_test_result`
    FOREIGN KEY (`patient_id_test_result`)
    REFERENCES `Hospital`.`Patients` (`patients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `lab_test_id_test_result`
    FOREIGN KEY (`lab_test_id_test_result`)
    REFERENCES `Hospital`.`LabTest` (`labTest_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `doctor_id_test_result`
    FOREIGN KEY (`doctor_id_test_result`)
    REFERENCES `Hospital`.`Doctors` (`doctors_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Rooms` (
  `rooms_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `room_number` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`rooms_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Admissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Admissions` (
  `admissions_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `patient_id_admissions` BIGINT(20) NOT NULL,
  `room_id_admissions` BIGINT(20) NOT NULL,
  `admission_date` DATE NOT NULL,
  `discharge_date` DATE NULL,
  PRIMARY KEY (`admissions_id`),
  INDEX `patient_id_admissions_idx` (`patient_id_admissions` ASC) VISIBLE,
  INDEX `room_id_admissions_idx` (`room_id_admissions` ASC) VISIBLE,
  CONSTRAINT `patient_id_admissions`
    FOREIGN KEY (`patient_id_admissions`)
    REFERENCES `Hospital`.`Patients` (`patients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `room_id_admissions`
    FOREIGN KEY (`room_id_admissions`)
    REFERENCES `Hospital`.`Rooms` (`rooms_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Medications` (
  `medications_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `descriptions` VARCHAR(200) NOT NULL,
  `manufacturer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`medications_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Prescriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Prescriptions` (
  `prescriptions_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `patient_id_prescriptions` BIGINT(20) NOT NULL,
  `doctor_id_prescriptions` BIGINT(20) NOT NULL,
  `medication_id_prescriptions` BIGINT(20) NOT NULL,
  `dosage` VARCHAR(50) NOT NULL,
  ` frequency` VARCHAR(50) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`prescriptions_id`),
  INDEX `id_doctor_idx` (`doctor_id_prescriptions` ASC) VISIBLE,
  INDEX `id_medication_idx` (`medication_id_prescriptions` ASC) VISIBLE,
  CONSTRAINT `patient_id_prescriptions`
    FOREIGN KEY (`patient_id_prescriptions`)
    REFERENCES `Hospital`.`Patients` (`patients_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `doctor_id_prescriptions`
    FOREIGN KEY (`doctor_id_prescriptions`)
    REFERENCES `Hospital`.`Doctors` (`doctor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `medication_id_prescriptions`
    FOREIGN KEY (`medication_id_prescriptions`)
    REFERENCES `Hospital`.` Medications` (` medications_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Hospital`.`Billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Billing` (
  `billing_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `patient_id_billing` BIGINT(20) NOT NULL,
  `admission_id_billing` BIGINT(20) NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `paid_amount` DECIMAL(10,2) NOT NULL,
  `billing_date` DATE NOT NULL,
  `payment_status` VARCHAR(45) NOT NULL,
  `labtest_id_billing` BIGINT(20) NOT NULL,
  PRIMARY KEY (`billing_id`),
  INDEX `patient_id_billing_idx` (`patient_id_billing` ASC) VISIBLE,
  INDEX `admission_id_billing_idx` (`admission_id_billing` ASC) VISIBLE,
  INDEX `labtest_id_billing_idx` (`labtest_id_billing` ASC) VISIBLE,
  CONSTRAINT `patient_id_billing`
    FOREIGN KEY (`patient_id_billing`)
    REFERENCES `Hospital`.`Patients` (`patients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `admission_id_billing`
    FOREIGN KEY (`admission_id_billing`)
    REFERENCES `Hospital`.`Admissions` (`admissions_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `labtest_id_billing`
    FOREIGN KEY (`labtest_id_billing`)
    REFERENCES `Hospital`.`LabTest` (`labTest_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
