-- MySQL Script generated by MySQL Workbench
-- Mon Jan 20 22:41:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hospital` DEFAULT CHARACTER SET utf8 ;
USE `Hospital` ;

-- -----------------------------------------------------
-- Table `Hospital`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Departments` (
  `id_department` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_department`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Doctors` (
  `id_doctor` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `specialization` VARCHAR(45) NOT NULL,
  `id_department` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_doctor`),
  INDEX `id_department_idx` (`id_department` ASC) VISIBLE,
  CONSTRAINT `id_department`
    FOREIGN KEY (`id_department`)
    REFERENCES `Hospital`.`Departments` (`id_department`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Nurses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Nurses` (
  `id_nurse` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `assigned_id_department` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_nurse`),
  INDEX `assigned_id_department_idx` (`assigned_id_department` ASC) VISIBLE,
  CONSTRAINT `assigned_id_department`
    FOREIGN KEY (`assigned_id_department`)
    REFERENCES `Hospital`.`Departments` (`id_department`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Patients` (
  `id_patient` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `contact_number` INT NOT NULL,
  PRIMARY KEY (`id_patient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Appointments` (
  `id_appointments` INT NOT NULL AUTO_INCREMENT,
  `id_patient` INT NOT NULL,
  `id_doctor` INT NOT NULL,
  `appointment_date` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_appointments`),
  INDEX `id_patient_idx` (`id_patient` ASC) VISIBLE,
  INDEX `id_doctor_idx` (`id_doctor` ASC) VISIBLE,
  CONSTRAINT `id_patient`
    FOREIGN KEY (`id_patient`)
    REFERENCES `Hospital`.`Patients` (`id_patient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_doctor`
    FOREIGN KEY (`id_doctor`)
    REFERENCES `Hospital`.`Doctors` (`id_doctor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`LabTest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`LabTest` (
  `id_lab_test` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_lab_test`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`TestResults`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`TestResults` (
  `id_test_results` INT NOT NULL,
  `id_patient` INT NOT NULL,
  `id_lab_test` INT NOT NULL AUTO_INCREMENT,
  `test_date` DATE NOT NULL,
  `result` VARCHAR(45) NOT NULL,
  `id_doctor` INT NOT NULL,
  PRIMARY KEY (`id_test_results`),
  INDEX `id_patient_idx` (`id_patient` ASC) VISIBLE,
  INDEX `id_lab_test_idx` (`id_lab_test` ASC) VISIBLE,
  INDEX `id_doctor_idx` (`id_doctor` ASC) VISIBLE,
  CONSTRAINT `id_patient`
    FOREIGN KEY (`id_patient`)
    REFERENCES `Hospital`.`Patients` (`id_patient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_lab_test`
    FOREIGN KEY (`id_lab_test`)
    REFERENCES `Hospital`.`LabTest` (`id_lab_test`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_doctor`
    FOREIGN KEY (`id_doctor`)
    REFERENCES `Hospital`.`Doctors` (`id_doctor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Rooms` (
  `id_room` INT NOT NULL AUTO_INCREMENT,
  `room_number` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`id_room`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Admissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Admissions` (
  `id_admissions` INT NOT NULL AUTO_INCREMENT,
  `id_patient` INT NOT NULL,
  `id_room` INT NOT NULL,
  `admission_date` DATE NOT NULL,
  `discharge_date` DATE NULL,
  PRIMARY KEY (`id_admissions`),
  INDEX `id_patient_idx` (`id_patient` ASC) VISIBLE,
  INDEX `id_room_idx` (`id_room` ASC) VISIBLE,
  CONSTRAINT `id_patient`
    FOREIGN KEY (`id_patient`)
    REFERENCES `Hospital`.`Patients` (`id_patient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_room`
    FOREIGN KEY (`id_room`)
    REFERENCES `Hospital`.`Rooms` (`id_room`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.` Medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.` Medications` (
  `id_medications` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `descriptions` VARCHAR(200) NOT NULL,
  `manufacturer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_medications`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.` Prescriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.` Prescriptions` (
  `id_prescriptions` INT NOT NULL AUTO_INCREMENT,
  `id_patient` INT NOT NULL,
  `id_doctor` INT NOT NULL,
  `id_medication` INT NOT NULL,
  `dosage` VARCHAR(50) NOT NULL,
  ` frequency` VARCHAR(50) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`id_prescriptions`),
  INDEX `id_doctor_idx` (`id_doctor` ASC) VISIBLE,
  INDEX `id_medication_idx` (`id_medication` ASC) VISIBLE,
  CONSTRAINT `id_patient`
    FOREIGN KEY (`id_patient`)
    REFERENCES `Hospital`.`Patients` (`id_patient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_doctor`
    FOREIGN KEY (`id_doctor`)
    REFERENCES `Hospital`.`Doctors` (`id_doctor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_medication`
    FOREIGN KEY (`id_medication`)
    REFERENCES `Hospital`.` Medications` (`id_medications`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Billing` (
  `id_billing` INT NOT NULL AUTO_INCREMENT,
  `id_patient` INT NOT NULL,
  `id_admission` INT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL,
  `paid_amount` DECIMAL(10,2) NOT NULL,
  `billing_date` DATE NOT NULL,
  `payment_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_billing`),
  INDEX `id_patient_idx` (`id_patient` ASC) VISIBLE,
  INDEX `id_admission_idx` (`id_admission` ASC) VISIBLE,
  CONSTRAINT `id_patient`
    FOREIGN KEY (`id_patient`)
    REFERENCES `Hospital`.`Patients` (`id_patient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_admission`
    FOREIGN KEY (`id_admission`)
    REFERENCES `Hospital`.`Admissions` (`id_admissions`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
